config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "stations#index"

  # I like the way you've structured your routes overall, though I have a couple suggestions.

  resources :stations do
    resources :bikes
  end

  # I suggest the following...
  # resources :users do
  #   resources :userbikes
  # end

  resources :userbikes do
    # the line below might complicate your controller code. Consider the example below from your Userbikes controller...
    #       @bike = Bike.find(params[:bike_id])
    # @bike could end up referring to a Bike with the same id as a User
    resources :users, :bikes
  end

  # see my note in UserbikesController
  get '/userbikes/:bike_id/checkout' => 'userbikes#checkout'

end

app/models/station.rb
class Station < ApplicationRecord
  has_many :bikes
  validates :station_name, :location, :photo_url, {presence: true}
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :edit, :destroy, :new]

  # create update and delete should have conditional error handling for failure


  def index
    @stations = Station.all
  end

  def new
   @station = Station.new
 end

  def create
    @station = Station.find(params[:station_id])
    @bike = @station.bikes.create(bike_params)
    redirect_to new_station_bike_path(@station, @bike)
  end

  def show
    @station = Station.find(params[:id])
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    @station.update(station_params)
    redirect_to root_path(@station)
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy(station_params)
    redirect_to root_path(@station)
  end

 def add_userbikes
    @bike = bike.find(params[:id])
    @bike.userbikes.create(user: current_user)
    redirect_to :back
  end

 def remove_userbike
    userbike.find_by(user: current_user, bike_id: params[:id]).destroy
    redirect_to :back
  end

  private
  def station_params
    params.require(:station).permit(:station_name, :location, :photo_url)
  end

end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/edit.html.erb
<h2>Update Station</h2>

<%= form_for([@station]) do |f| %>

  <%= f.label :station_name %>
  <%= f.text_field :station_name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :photo_url %>
  <%= f.text_field :location %>

  <%= f.submit %>

<% end %>

<%= link_to 'Delete!', stations_path(@station), method: :delete, class: 'delete' %>

app/views/stations/index.html.erb
<h1>Welcome to Bikeshares App</h1>
<h3>Please choose a station to see the availability of bikes.</h3>

<div class="box">
  <h2>List of Stations</h2>
<ul>
  <% @stations.each do |station| %>
    <li>
      <a href="/stations/<%= station.id %>">
        <%= station.station_name %>
      </a>
    </li>
  <% end %>
</ul>
</div>


<div id='bike'>
  <img src="http://i.imgur.com/h0J8x34.png" alt="cat">
</div>

app/views/stations/new.html.erb
<h2>Create Station</h2>

<%= form_for([@station]) do |f| %>

  <%= f.label :station_name %>
  <%= f.text_field :station_name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :photo_url %>
  <%= f.text_field :location %>

  <%= f.submit %>

<% end %>

app/views/stations/show.html.erb
  <h3> Name of Station: <%= @station.station_name %></h3>
  <h3> Address: <%= @station.location %></h3>
  <h3><img src="<%= @station.photo_url %>"></h3>

  <h3><a href="/stations/<%= @station.id %>/bikes/<%= @bike_station %>">Find bikes in this station</a></h3>
  <h3><a href="/stations/<%= @station.id %>/bikes/new">Create Bikes</a></h3>
  <h3><a href="/stations/<%= @station.id %>/edit">Update Station</a></h3>